server:
  port: ${PORT}

jwt:
  token: ${JWT_TOKEN}
  expiry: ${JWT_EXPIRY}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

bot:
  token: ${BOT_TOKEN}

cloudinary:
  cloud_name: ${CLOUDINARY_NAME}
  api_key: ${CLOUDINARY_KEY}
  api_secret: ${CLOUDINARY_SECRET}
